# Generated by Django 5.2.14 on 2026-05-21 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('category', models.CharField(max_length=120, verbose_name='categoria')),
                ('sector', models.CharField(choices=[('escritorio', 'Escritorio'), ('limpeza', 'Limpeza'), ('manutencao', 'Manutencao')], max_length=30, verbose_name='setor')),
                ('current_quantity', models.PositiveIntegerField(default=0, verbose_name='quantidade atual')),
                ('minimum_quantity', models.PositiveIntegerField(default=0, verbose_name='quantidade minima')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='localizacao')),
                ('last_entry_at', models.DateTimeField(blank=True, null=True, verbose_name='ultima entrada')),
                ('last_exit_at', models.DateTimeField(blank=True, null=True, verbose_name='ultima saida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sector', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida')], max_length=20, verbose_name='tipo')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='estoque.stockitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
