# Generated by Django 5.2.14 on 2026-06-01 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0001_initial'),
        ('estoque', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='condominium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='condominios.condominium', verbose_name='condominio'),
        ),
    ]
