# Generated by Django 5.2.14 on 2026-06-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0001_initial'),
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authorized_condominiums',
            field=models.ManyToManyField(blank=True, to='condominios.condominium', verbose_name='condominios autorizados'),
        ),
    ]
