# Generated by Django 5.2.14 on 2026-05-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('escritorio', 'Escritorio'), ('limpeza', 'Limpeza'), ('manutencao', 'Manutencao'), ('area_externa', 'Area externa'), ('outros', 'Outros')], max_length=30, verbose_name='setor')),
                ('description', models.TextField(verbose_name='descricao do problema')),
                ('priority', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20, verbose_name='prioridade')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('aguardando_peca', 'Aguardando peca'), ('concluido', 'Concluido')], default='aberto', max_length=30, verbose_name='status')),
                ('opening_photo', models.ImageField(blank=True, upload_to='chamados/abertura/', verbose_name='foto de abertura')),
                ('completion_photo', models.ImageField(blank=True, upload_to='chamados/conclusao/', verbose_name='foto de conclusao')),
                ('solution', models.TextField(blank=True, verbose_name='solucao aplicada')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='data de conclusao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='aberto em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
