# Generated by Django 5.2.14 on 2026-05-22 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=20, verbose_name='canal')),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Falhou'), ('skipped', 'Nao configurado')], max_length=20, verbose_name='status')),
                ('message', models.TextField(blank=True, verbose_name='mensagem')),
                ('response', models.TextField(blank=True, verbose_name='resposta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chamados.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
